- name: Run Proxy Container
  docker_container:
    name: httpd
    image: "{{ secrets.DOCKERHUB_USERNAME }}/tp-devops-proxy:latest"
    pull: true
    networks:
      - name: app-network
    ports:
      - "80:80"
    state: started
    restart_policy: always