---
- name: Run Backend App Container
  docker_container:
    name: backend
    image: madow78/tp-devops-backend
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/db"
      SPRING_DATASOURCE_USERNAME: "usr"
      SPRING_DATASOURCE_PASSWORD: "pwd"
    state: started
    restart_policy: always
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
