name: CI devops 2026

on:
  push:
    branches: 
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  # 1. Tests (Lancement immédiat)
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Backend Tests
        run: mvn -B clean verify --file backend/pom.xml

  # 2. Sonar (Attend les tests)
  sonar-analysis:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: SonarCloud Analysis
        run: mvn -B verify sonar:sonar -DskipTests --file ./backend/pom.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 3. Image Backend (Attend Sonar)
  build-image-backend:
    needs: sonar-analysis
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest

  # 4. Image Front (Lancement immédiat, parallèle au backend)
  build-image-front:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Front
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-front:latest

  # 5. Image Database (Lancement immédiat, parallèle au backend)
  build-image-database:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

  # 6. Deploy (Attend les 3 images)
  deploy:
    needs: [build-image-backend, build-image-front, build-image-database]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml \
          --private-key ~/.ssh/id_rsa \
          -u admin \
          --ssh-common-args='-o StrictHostKeyChecking=no'
